name: 'AWS-terraform-workflow'

on:
  workflow_dispatch:



jobs:
   first-job:
       name: "terraform-automate"
       runs-on: ubuntu-latest

       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
         AWS_DEFAULT_REGION: us-east-1

       steps:
         - name: Checkout
           uses: actions/checkout@v1

         - name: Setup Terraform
           uses: hashicorp/setup-terraform@v1

         - name: Terraform Init
           working-directory: ./pipeline-aws
           run: terraform init -reconfigure
           

         - name: Terraform-apply
           working-directory: ./pipeline-aws
           run: terraform apply -auto-approve -input=false
